
configfile: "config/pipeline.yml"


### Setup sample inputs
import os
from glob import glob

SAMPLE = [
    os.path.basename(fn).replace("_1.fq.gz", "")
    for fn in glob(f"resources/reads/*_1.fq.gz")
]

print("Detected the following samples:")
print(SAMPLE)


include: "rules/folders.smk"
include: "rules/fastp.smk"
include: "rules/ribodetector.smk"
include: "rules/star.smk"


rule all:
    input:
        # expand(FASTP / "{sample}_1.fq.gz", sample=SAMPLE),
        # expand(RIBO / "{sample}_1.fq.gz", sample=SAMPLE),
        STAR / "index",
        expand(STAR / "{sample}.Aligned.sortedByCoord.out.bam", sample=SAMPLE),
        expand(STAR / "{sample}.Unmapped.out.mate1.fq.gz", sample=SAMPLE),
