 name: 3Domics_Macro_Host_Transcriptomics
 channels:
    - conda-forge
    - bioconda
    - defaults
 dependencies:
    - fastp=0.23.2
    - star=2.7.10a
    - pigz=2.3.4
    - ribodetector=0.2.7
    - gffread=0.12.7
